# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11
  
  - repo: local
    hooks:
      - id: pytest-check
        name: Run tests
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]